### ISSUE TITLE
cts run failed

### ISSUE THREAD

**Issue by unicornx** [riscv-android-src/platform-cts#2]
[cts-20220705-01.log](https://github.com/riscv-android-src/platform-cts/files/9044784/cts-20220705-01.log)

I run with `run cts -s emulator-5556 -m CtsOsTestCases -t android.os.cts.BuildTest#testBuildConstants --disable-reboot --skip-device-info --skip-all-system-status-check --skip-preconditions`
But I'm afraid there's no case running, why?

**Comment by zhangye** [comment]
Please check your devices property "ro.product.cpu.abilist"

adb shell getprop | grep ro.product.cpu.abilist
[ro.product.cpu.abilist]: [riscv64]
[ro.product.cpu.abilist32]: []
[ro.product.cpu.abilist64]: [riscv64]

**Comment by zhangye** [comment]
cd tools/tradefederation/core/
git log

commit 80273037f33b5f73e7e0d68cddf4f07f77e7d337 (HEAD, m/riscv64-android-12.0.0_dev, github/riscv64-android-12.0.0_dev, aosp/riscv64-android-12.0.0_dev)
Author: uCR-Dev <dev@ucrobotics.com>
Date:   Thu Feb 4 07:37:36 2021 +0000

    AbiUtils: Add RISCV Support
    AbiUtils.java: Support RISCV64 and RISCV.
    
    Change-Id: I5bb16855500e98d1d26a885b997b913a3a177f42

**Comment by unicornx** [comment]
After `m clean` and `m cts` + `m`. I run the cts testing again.

Attachment is the new log, seems different against last one:
- No getAbi error this time.
- number of Total Tests is 1, not zero now.
- but there are still many errors, and I see the last error reports the device/emulator doesn't response, not sure if it's due to the test reboot the device？But I tried `adb shell` and the emulator still works.

console input and output log
[cts-20220706-01.txt](https://github.com/riscv-android-src/platform-cts/files/9050634/cts-20220706-01.txt)

tradefed's log from /tmp
[tradefed_global_log_16627945192014792339.txt](https://github.com/riscv-android-src/platform-cts/files/9050635/tradefed_global_log_16627945192014792339.txt)

**Comment by zhangye** [comment]
CT depends on art and boot completion.
You need to wait about 30 minutes for boot completion on the emulator.
Or you can wait about 2 minutes for boot completion on the RISCV board.

Or you can try VTS, it doesn't depends on art and boot completion.

**Comment by zhangye** [comment]
ART is not ready, please disable JIT and dex2oat.

diff --git a/runtime/jit/jit.h b/runtime/jit/jit.h
index a6e484f563..e8126669a2 100644
--- a/runtime/jit/jit.h
+++ b/runtime/jit/jit.h
@@ -122,7 +122,7 @@ class JitOptions {
   }
 
   bool UseJitCompilation() const {
-    return use_jit_compilation_;
+    return false;//use_jit_compilation_;
   }
 
   bool UseProfiledJitCompilation() const {
diff --git a/runtime/thread.h b/runtime/thread.h
index 7a408021c1..1d0f421106 100644
--- a/runtime/thread.h
+++ b/runtime/thread.h
@@ -1277,7 +1277,7 @@ class Thread {
   }
 
   bool IsForceInterpreter() const {
-    return tls32_.force_interpreter_count != 0;
+    return true;//tls32_.force_interpreter_count != 0;
   }

**Comment by unicornx** [comment]
> diff --git a/runtime/jit/jit.h b/runtime/jit/jit.h index a6e484f563..e8126669a2 100644 --- a/runtime/jit/jit.h +++ b/runtime/jit/jit.h @@ -122,7 +122,7 @@ class JitOptions { }
> 
> bool UseJitCompilation() const {
> 
> * return use_jit_compilation_;
> 
> * return false;//use_jit_compilation_;
>   }
> 
> bool UseProfiledJitCompilation() const { diff --git a/runtime/thread.h b/runtime/thread.h index 7a408021c1..1d0f421106 100644 --- a/runtime/thread.h +++ b/runtime/thread.h @@ -1277,7 +1277,7 @@ class Thread { }
> 
> bool IsForceInterpreter() const {
> 
> * return tls32_.force_interpreter_count != 0;
> 
> * return true;//tls32_.force_interpreter_count != 0;
>   }

correct code as below:

```
diff --git a/runtime/jit/jit.h b/runtime/jit/jit.h
index a6e484f563..e8126669a2 100644
--- a/runtime/jit/jit.h
+++ b/runtime/jit/jit.h
@@ -122,7 +122,7 @@ class JitOptions {
}

bool UseJitCompilation() const {

- return use_jit_compilation_;
+ return false;//use_jit_compilation_;
}
bool UseProfiledJitCompilation() const {
diff --git a/runtime/thread.h b/runtime/thread.h
index 7a408021c1..1d0f421106 100644
--- a/runtime/thread.h
+++ b/runtime/thread.h
@@ -1277,7 +1277,7 @@ class Thread {
}

bool IsForceInterpreter() const {

- return tls32_.force_interpreter_count != 0;
+ return true;//tls32_.force_interpreter_count != 0;
}
```

**Comment by unicornx** [comment]
closed due to I'm not working on this now.
